### ISSUE TITLE
Form Factor

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Line_trigger#1]
For things like this in a standalone box, can you make it a reasonable HP high and then sell optional 'ears' so that it can go in a Eurocard crate? Like how they make a lot of IT equipment 1U high so you can buy ears to mount it in a 19" rack:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/20587606/93286340-e1db9380-f78b-11ea-9cf7-01aa93d1c996.png">

Another idea would be just adding this functionality to [3U PSU](https://github.com/sinara-hw/meta/issues/47).  Once you have access to the mains and DC power, the extra components to implement a line trigger are pretty trivial right (like a couple $ on the BOM)?  Then everyone has a convenient line trigger if/when they ever need it.

**Comment by gkasprow** [comment]
3U psu uses SMPS. We need standard isolation transformer, but it wont fit. Even the smallest one.We can make optocoupler version or make high impedance mains divider directly. I will try to fit in in the new release.

**Comment by gkasprow** [comment]
The easiest way to go is to make a 1U panel with cutout to which the standard Hammond box is attached. The product can be delivered with both panels so the user can choose which one to attach.

**Comment by hartytp** [comment]
My feeling is that making this rack mount is way overkill. I was thinking of something more like an extruded enclosure the size of thermostat.

**Comment by hartytp** [comment]
(or, at least as small as the 50Hz transformer allows)

**Comment by dtcallcock** [comment]
>The easiest way to go is to make a 1U panel with cutout to which the standard Hammond box is attached.

>making this rack mount is way overkill

Sorry, I meant using the same 'ears' idea to mount it in a Eurocard subrack.

> an extruded enclosure the size of thermostat.

Here's another idea.  Use an 24V [ac-ac plug transformer](https://www.jameco.com/c/AC/AC-Power-Supplies.html) to power the board.  The you don't need a bulky transformer or mains connector on the board, and it can be open.  From there you can copy thermostat mechanics (options for Eurocard or standalone).

> 3U psu uses SMPS. 

Ok, I forgot this.  Perhaps this isn't a great idea then.

**Comment by hartytp** [comment]
> Use an 24V ac-ac plug transformer to power the board. 
> From there you can copy thermostat mechanics (options for Eurocard or standalone).

That's a nice idea.

**Comment by gkasprow** [comment]
Yes, and we will provide compatibility with 110, 230, and other voltages. The filter can support 50 and 60Hz at once.

**Comment by hartytp** [comment]
Since this is a low frequency design can we have FP dip switches for frequency/filter bandwidth selection?

**Comment by gkasprow** [comment]
Yes, we can do that. No need to put it on the FP because we will need at least 8 dip switches and once set, never touch again.

**Comment by dtcallcock** [comment]
Worth using a connector that's incompatible with the standard 12V DC barrel used throughout Sinara to prevent mixups?

**Comment by gkasprow** [comment]
I was thinking about it. 2.1mm one won't let you plug 12V AC to Kasli (it has 2.5mm one), but will let you plug DC PSU to the trigger box, but nothing will happen.

**Comment by dhslichter** [comment]
I think you want a small plastic box which can basically be installed inline on a mains power line (IEC on both sides?  Then someone can use a double-ended IEC cable to adapt out, we ship with such a cable), and have an isolated SMA or BNC on the side with the trigger output.

**Comment by hartytp** [comment]
> I think you want a small plastic box which can basically be installed inline on a mains power line (IEC on both sides? Then someone can use a double-ended IEC cable to adapt out, we ship with such a cable), and have an isolated SMA or BNC on the side with the trigger output.

The advantage of an AC/AC adapter as suggested by @dtcallcock is not having to worry about mains safety, which does seem like a good idea.

I also wouldn't bother having an IEC on both sides as putting this inline with another powered device seems like a waste of time (mains sockets aren't that precious!).

**Comment by dhslichter** [comment]
fair.  it was just an idea for compactness, but something that looks like a wall wart power supply but has an isolated SMA coming out for line trigger info would be a cute little product.

**Comment by hartytp** [comment]
> but something that looks like a wall wart power supply but has an isolated SMA coming out for line trigger info would be a cute little product.

If I understood @dtcallcock's proposal correctly, it's not quite that. Rather, it's a small enclosure that takes in ~9V AC (50/60Hz) from a wall wart (barrel connector that's incompatible with the one used on Kasli et al.) and has a out a couple of SMA/MCX/whatever outputs.

**Comment by dhslichter** [comment]
why break it into two components like that?

**Comment by gkasprow** [comment]
- safety
- support for 110 and 230V
