### ISSUE TITLE
filter design

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Line_trigger#2]
This is the proposed filter design
![obraz](https://user-images.githubusercontent.com/4325054/93314858-9d430d00-f80a-11ea-90f3-c925cddaad02.png)

and the response including tolerances
![obraz](https://user-images.githubusercontent.com/4325054/93314895-acc25600-f80a-11ea-9e17-ddf19f00b296.png)

**Comment by jordens** [comment]
I don't want to spoil the fun, but isn't this overkill? 
Assuming some reasonable limit on the stability (and thus bandwidth) of any realistic mains-synchronized signal that is to be canceled, of let's say 1e-2 or maybe even 1e-3, then shouldn't a simple pair of zeners and a resistor hotwired into a mains plug be sufficient? https://www.onsemi.com/pub/Collateral/AND9282-D.PDF We have isolation in the digital inputs, this wouldn't need power supplies, any special case, mounting brackets, filter design.

**Comment by gkasprow** [comment]
This would be true if the mains was ideal sinusoid. In fact, it is often heavily distorted, both by missing PFC in SMPS and triac dimmers. That's why ot provide low jitter, it's good to filter the main component and then feed the comparator.
I wouldn't connect the digital inputs to mains due to safety. touching the BNC can be lethal hazard. The simplest aproach would be just an optocoupler fed by the mains signal with Zener and resistor.

**Comment by jordens** [comment]
That distortion and its variability is precisely the limit in cancelling a mains cycle effect and feeding forward such a cancellation signal. What's the point in timing with respect to the fundamental if your feed forward signal has high harmonic content? I can see how being very narrowband will actually decrease robustness/stability to changes in the distortion.

**Comment by gkasprow** [comment]
that's a good question. A long time ago I saw such a circuit somewhere at CERN, but they used a flywheel generator, so that could make sense...

**Comment by jordens** [comment]
The PS rotating machine may well benefit from this ;)

**Comment by gkasprow** [comment]
What I can do, is to add a jumper that selects the signal from before the filter or after the filter. In this way we can easily compare if that makes any sense.

**Comment by hartytp** [comment]
> That distortion and its variability is precisely the limit in cancelling a mains cycle effect and feeding forward such a cancellation signal. What's the point in timing with respect to the fundamental if your feed forward signal has high harmonic content? I can see how being very narrowband will actually decrease robustness/stability to changes in the distortion.

yes, the optimal solution here depends on the application. But, having something that can remove the higher frequency in the noise is cheap to implement and useful in at least some cases.

@gkasprow can we use the same OpAmp as Zotino here? Low cost, low power consumption and better component reuse between designs (we must be buying in ku now with Fastino/Zotino?). Maybe also have a passive RF filter before the OpAmps to remove out-of-bandwidth signals?

**Comment by hartytp** [comment]
what are those big output capacitors?

**Comment by gkasprow** [comment]
> what are those big output capacitors?

oh, this is a reference generation circuit. The schematic was generated by ADI tool
Sure, we can reuse opamps from Zotino, but in this case, even the cheapest LM324 will do the job.

**Comment by gkasprow** [comment]
@hartytp Take a quick look at this schematic
Supply
![obraz](https://user-images.githubusercontent.com/4325054/93690879-0dd57c80-fade-11ea-8821-1ef4a17e30cc.png)
filter + comparator
![obraz](https://user-images.githubusercontent.com/4325054/93690886-1928a800-fade-11ea-8434-43a7c67f7cf7.png)

Making the circuit 50/60Hz would require placing 8 switches + 8 caps. I think the existing circuit will work for 60Hz as well. If somebody wants, one can install 27nF caps instead of 33nF ones or order such a version.

Initial placement
![obraz](https://user-images.githubusercontent.com/4325054/93690921-889e9780-fade-11ea-8f6e-227592a403d9.png)

**Comment by dtcallcock** [comment]
> I think the existing circuit will work for 60Hz as well.

How about just centering the BPF at 55Hz?

**Comment by gkasprow** [comment]
30nF capacitors would do that. You simply order 60Hz/110V version and you get it with right capacitors and AC adapter
