### ISSUE TITLE
schematic issues

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Line_trigger#3]
looking at https://github.com/sinara-hw/Line_trigger/issues/2#issuecomment-695365925

- [x] IC1 requires a NR capacitor for stability. 1uF recommended
- [x] confirm voltage ratings on LDO input/output capacitors (e.g. IC1 recommends 47uF on the output, we have 2x22uF which could end up being a lot lower under bias depending on the selected capacitor type). Similarly, the input requires a min of 10uF. We have 22uF but that could wind up marginal once bias is taken into account. Same goes for the negative LDO (e.g. is the FB capacitor large enough under bias?)
- [x] worth having a CMC/line filter on the input?
- [x] why is there a reverse bias diode on the output of the negative LDO and not the positive? I'd put one on both to be safe
- [x] isn't 680Ohm a bit on the low side for driving LEDs from 5V?
- [x] negative LDO NR recommendation is 1uF
- [x] negative LDO output capacitor recommendation is 47uF (under bias)
- [x] the schematic annotation says 1W max for the input power. Surely we can't use anything close to that can we???
- [x] for the negative LDO we might as well stick with their feedback resistor choices to ensure the RC poles are where the IC designers want them

![image](https://user-images.githubusercontent.com/21218399/93707548-9f1d1100-fb27-11ea-9c7b-767eff1cc65f.png)

I'm not going to look at the active filter topology / component selection in detail. The transfer function you posted looked sensible.

- [x] were we planning to have a DIP switch/(solder?) jumper to allow the filter to be bypassed?
- [x] should we add a small feedback capacitor on the comparator to help stabilize it (the slew rate on the input is quite low so may lead to instability) and give nice sharp edges? This is a very fast comparator so I'd worry about oscillations when driven by a 50Hz signal...
- [x] can you add a suitable AC/AC adaptor with the right connector to the schematic/BOM so we make sure all users use the same part (less work to debug than if everyone picks their own!)
- [x] SN74LVT125 is recommended for 3V3 max operation
- [x] the output buffer has to drive a 100Ohm load so might be wroth a tantalum capacitor by it..

Otherwise, looks good to me! Let's get it made :)

**Comment by hartytp** [comment]
Maybe add a schematic annotation/design variant for 60Hz?

**Comment by gkasprow** [comment]
if we load both outputs with 50Ohm, we end up with 1W
The comparator already has hysteresis, I added a DNP capacitor
Right, I meant LV125 which works at 5V and is capable of driving 100Ohm loads.
I added a 47uF cap to the output buffer supply + FB. Not worth increasing the BOM with a tantalum cap.

**Comment by hartytp** [comment]
@gkasprow Aren’t there already tantalum caps after the rectifier (not that it matters, I’m happy either way).

It’s 500mW max isn’t it since it’s 2.5V AC into 100 ohm in two channels?

**Comment by hartytp** [comment]
Anyway I’m happy to move to manufacture when you are.

Thanks for the nice work on this :)

**Comment by gkasprow** [comment]
Yes, 500mW dissipates on the load. Add the LDO efficiency :)

**Comment by hartytp** [comment]
Oops!

**Comment by gkasprow** [comment]
Oh, OK, I asumed permanent state H. Of course we have 50% duty cycle.

**Comment by hartytp** [comment]
For anyone following: the plan is to get TS to produce a batch shortly. Contact Greg/Pawel if you're interested...

**Comment by dtcallcock** [comment]
> the plan is to get TS to produce a batch shortly

Will you post a final design for review or do you need to get this off yesterday (not a huge deal but always good to have more eyes)?

>can you add a suitable AC/AC adaptor with the right connector to the schematic/BOM so we make sure all users use the same part (less work to debug than if everyone picks their own!)

Good idea but you need one for each region.  [This one](http://catalog.triadmagnetics.com/Asset/WAU12-200.pdf) looks readily available in the US.  It has a 2.1x5.5mm plug as suggested.  It's 11mm long - does that length work?

I've definitely seen those wall wart transformers put out higher than specified voltage under light load.  Looks like the regs can take 36V which should be plenty, but might be worth selecting caps with a similar rating if you didn't already.

**Comment by gkasprow** [comment]
the schematics are in the repo

**Comment by hartytp** [comment]
> Will you post a final design for review or do you need to get this off yesterday (not a huge deal but always good to have more eyes)?

There is no mad rush, but I need to keep things moving through my to do list for sanity's sake...

> I've definitely seen those wall wart transformers put out higher than specified voltage under light load. Looks like the regs can take 36V which should be plenty, but might be worth selecting caps with a similar rating if you didn't already.

Yes, good point. @gkasprow are you happy that the OpAmp circuit will still function happily if the voltage comes out a bit high?

**Comment by dtcallcock** [comment]
>Good idea but you need one for each region. This one looks readily available in the US. It has a 2.1x5.5mm plug as suggested. It's 11mm long - does that length work?

The [722RA](http://www.switchcraft.com/Product.aspx?ID=7049) you are using mates with the [S760](http://www.switchcraft.com/Product.aspx?ID=2588) which is 9.5mm long, so this will work.

> the schematics are in the repo

Does IC8 need a 10nF decoupling cap? Other than that, I didn't see anything else.

**Comment by gkasprow** [comment]
we don't want the voltage to rise to 35V - the LDOs won't dissipate that much of power. Let's keep the capacitors as they are now.
